### ISSUE TITLE
Conflict with Limitless Mythic Abilities Added by Dark Codex

### ISSUE THREAD

**Issue by RobMatteson** [pheonix99/WotRResourceUnification#1]
[Dark Codex](https://github.com/Truinto/DarkCodex) adds mythic abilities that change limited use abilities to unlimited use. This mod seems to cause a conflict which makes abilities which use an affected resource to fail with the following message:

`Out of Resources:`

I can confirm the issue occurs with the following:

Limitless Arcane Pool
Limitless Arcane Reservoir

The following seemed to work ok:

Limitless Bardic Performance
Limitless Witch Hexes
Limitless Warpriest

I haven't had the opportunity to test the following:

Limitless Bombs
Limitless Domain
Limitless Ki
Limitless Shaman
Limitless Smite

**Comment by pheonix99** [comment]
I'll look into that.

**Comment by Truinto** [comment]
Looking at your code I didn't find a correlation. @RobMatteson did you rest at least once before testing this? If you have no resources the ability will be unavailable and not even check cost reducing features.

**Comment by RobMatteson** [comment]
@Truinto Yes, I tried resting but resources do not appear to restore. I also tried respecing mythic abilities and resting again, but no luck.

**Comment by pheonix99** [comment]
Fixed in v1.2

Owlcat did *something* that made my UnitAbilityResourceCollection.GetResource prefix break things. Fixed that.
